# -*- coding: utf-8 -*-
"""Data Visualization in Python Lab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qmKObmT0XsmwXXJdqOYQGwpOXm_tKtEU
"""



# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import random
random.seed(777)
v = [random.randint(-5,5) for k in range(20)]
plt.grid(True)
plt.plot(v, '-')
plt.show()

plt.plot(v, '-', linewidth = 6);

import random
random.seed(777)
v = [random.randint(-5,5) for k in range(20)]
plt.figure(figsize=[12,8])
plt.grid(True)
plt.plot(v, '-')
plt.show()

random.seed(777)
v = [random.randint(-5,5) for k in range(20)]
plt.figure(figsize=[12,8])
plt.title("A simple plot", size = 'x-large')
plt.ylabel('Y')
plt.xlabel('X')
plt.grid(True)
plt.plot(v, 'g-', linewidth = 6 );

random.seed(111)
mean, std = 0, 1
X = [random.gauss(mean, std) for i in range(1500)] 
plt.xlabel('Measurement')
plt.ylabel('Probability')
plt.title('Histogram of Measurements')
plt.grid(True)
plt.hist(X, 100, density=True, facecolor='b');

plt.subplot(222)
plt.plot(range(20), 'r+')
plt.subplot(221)
plt.plot(range(40), 'g.')
plt.subplot(224)
plt.plot(range(60), 'bx')
plt.subplot(223)
plt.plot(range(100),'c-' );

plt.plot(range(20), 'r+')
plt.savefig('simple_line.jpeg', dpi=600)

sns.set()

input_file = 'http://bit.ly/36je2mw' 
cars = pd.read_csv(input_file); cars.head(4)

cars.info()

sns.distplot (cars.hp);

sns.displot (x = cars.hp, kde=True, data=cars);

import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

sns.distplot (cars.hp, color='g', bins=20) ;

sns.jointplot(x="hp", y="wt", data=cars, kind="kde");

sns.boxplot(cars.qsec, palette='summer');

cars[cars.qsec > 22]

plt.figure(figsize=(4,8))
sns.boxplot(x = cars.cyl, y = cars.qsec, palette='inferno');

cars[cars.cyl == 4].qsec

sns.displot (x = cars[cars.cyl == 4].qsec, kde=True);

cars[cars.cyl == 4].qsec.describe()

sns.catplot(x='gear', y = 'mpg', data = cars);

sns.catplot(x='gear', y = 'mpg', data = cars, hue = 'cyl');

sns.catplot(x='gear', y = 'mpg', kind='box', data = cars);

sns.catplot(x='cyl', y = 'qsec', data = cars); #, hue = 'gear');

columns = ['hp', 'wt', 'mpg', 'cyl', 'disp', 'qsec']
df = cars [columns].copy()

df.shape

sns.pairplot(df);

sns.pairplot(df, hue='cyl');

df.info()

sns.set()
sns.heatmap(df.corr());

