# -*- coding: utf-8 -*-
"""kNN Lab

Automatically generated by Colaboratory.

"""

import sklearn as sk
import numpy as np
import pandas as pd

sk.__version__

input_file = 'http://bit.ly/2O7Islk'
all = pd.read_csv(input_file, header=None, sep=',')
all.head()

all.shape

c = all.loc[:,[57]]
c[c == 1].count(),  c[c == 0].count()

spamdb = all.loc[:, 0:56]

from sklearn.model_selection import train_test_split

labels = np.concatenate([[1 for i in range(1813)], [0 for i in range(2788)]])

data_train, data_test, label_train, label_test = train_test_split(spamdb, labels, test_size=0.3, random_state=0)

from sklearn.neighbors import KNeighborsClassifier
knnModel = KNeighborsClassifier(n_neighbors=3)
knnModel.fit(data_train, label_train)

label_predict = knnModel.predict(data_test)

import sklearn.metrics as metrics
metrics.confusion_matrix(label_test, label_predict)

knnModel.score(data_train, label_train)

knnModel.score(data_test, label_test)

knnModel2 = KNeighborsClassifier(n_neighbors=5, algorithm='kd_tree')

knnModel2.fit(data_train, label_train) 
label_predict2 = knnModel2.predict(data_test)
metrics.confusion_matrix(label_test, label_predict2)

