# -*- coding: utf-8 -*-
"""The k-means Project

Automatically generated by Colaboratory.

"""

from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix
import pandas as pd

input_file = 'http://bit.ly/2O7Islk'
all = pd.read_csv(input_file, header=None, sep=',')

true_labels = all[57]
all_features = all.iloc[:,:-1];

kspam = KMeans(n_clusters=2, random_state=0).fit(all_features)

print ("The k-means model dump:", kspam)

print ("The confusion matrix:\n", confusion_matrix(true_labels,kspam.labels_))

print("Inertia: ", kspam.inertia_)