# -*- coding: utf-8 -*-
"""The Titanic Project

Automatically generated by Colaboratory.

"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd

# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

input_file =  'http://bit.ly/2U18s5V' 
ship = pd.read_csv(input_file); ship.head(4)

ship.shape

ship.info()

ship = ship.rename(columns = {'Siblings/Spouses Aboard': 'SibSp', 'Parents/Children Aboard' : 'Parch' }); ship.columns

ship.Survived = ship['Survived'].astype('category')
ship['Pclass'] = ship.Pclass.astype('category')

sns.set()
sns.distplot (ship.Fare, color='g', bins=20) ;

plt.figure(figsize=[14,3])
sns.boxplot(x = ship.Fare);

ship [ship.Fare > 500]

sns.catplot(x='Survived', y = 'Fare', data = ship, hue='Pclass');

cols = ['Age', 'Fare', 'Survived']
df = ship [cols].copy()

sns.pairplot(df, hue='Survived');

ship[ship.Age > 70]

