# -*- coding: utf-8 -*-
"""Understanding NumPy Lab

Automatically generated by Colaboratory.

"""

import numpy as np

python_list = [1,2,3,4,5]
np_array = np.array( python_list )
type(np_array)

?np_array

# Commented out IPython magic to ensure Python compatibility.
# %quickref

type(np_array[0])

import re
for a in list(dir(np)):
    f = re.search('u?int\d+', a)
    if (f): print (f.string)

np_int32 = np.array( [1,2,3], dtype = np.int32)
type(np_int32[0])

np.array( ['1',2,3])

np.arange(12)

np.arange(12).shape

m = np.arange(12).reshape(3,4); m

m.shape?

n = np.arange(4); n

np.dot(m,n)

m

n + n

n + np.arange(5)

m * 1.1

m

np_array % 2 == 0

filter = np_array % 2 == 0
np_array [filter]

np_array

import numpy as np
np.random.seed(10)
sales = np.array((100 * np.random.rand (5)).astype(int)); sales

ra = np.random.rand(3,5); ra

ra.reshape(5,3)



ra.reshape(-1)

x = np.arange(0,10,3); x

x.reshape(-1,1)

x.reshape(-1,1) * [1,2]

a2 = np.arange(20).reshape(5,4); a2

a2.sum(axis = 0)

a2.sum(axis = 1)

a2.mean(axis = 0)

a2.mean(axis = 1)

a2.cumsum(axis=0)

a2.cumsum(axis=1)

np.linspace(-5,5,20)

np.sum(np.diff(np.linspace(-5,5,20)))