# -*- coding: utf-8 -*-
"""Understanding pandas Lab

Automatically generated by Colaboratory.

"""

import numpy as np
import pandas as pd

np.random.seed(10)
sales = np.array((100 * np.random.rand (5)).astype(int))
sales

location = [c for c in 'ABCDE']; location

data_np = np.array([sales, location])
data_np

df = pd.DataFrame(data_np, columns = ["Sales", "Location"])

data_np = np.array([sales, location]).T
data_np

df = pd.DataFrame(data_np, columns = ["Sales", "Location"])
df

df.dtypes

type(df.dtypes)

df.Sales = df.Sales.astype(int)

df.dtypes

df.describe()

df.describe?

df.Sales.sum() /df.Sales.count()

df.Sales.mean()

df.Location

df.Sales

df.loc[:, 'Sales']

df.loc[:2, 'Location']

df.iloc[-1, :]

df.Sales.sort_values(ascending=False)

df.Sales

df['Month'] = pd.DataFrame(['Jan', 'Feb', 'Mar', 'Apr', 'May']); df

del df['Month']

df1 = df.head(2)
df2 = df.tail(1)
df12 = pd.concat([df1, df2])
df12

df12 = pd.concat([df1, df2], ignore_index=True); df12

df12.index

url = 'http://bit.ly/36fGR32'
df2 = pd.read_csv(url)

df2.head()

df2.dtypes

df2.info()

